package media

import (
	"context"
	"fmt"
)

// OCRHandler extracts text from images using optical character recognition
type OCRHandler interface {
	// ExtractFromURL extracts text from an image at the given URL
	ExtractFromURL(ctx context.Context, imageURL string) (*OCRResult, error)
	// ExtractFromFile extracts text from a local image file
	ExtractFromFile(ctx context.Context, filePath string) (*OCRResult, error)
	// Close releases any resources
	Close() error
}

// OCRResult contains the output of OCR extraction
type OCRResult struct {
	// The extracted text content
	Text string
	// Confidence score from 0-1 (higher is better)
	ConfidenceScore float64
	// Language detected in the text
	Language string
	// Bounding boxes for detected text regions (optional)
	BoundingBoxes []TextBoundingBox
	// Raw response from OCR service (for debugging)
	RawResponse interface{}
}

// TextBoundingBox represents a region containing text
type TextBoundingBox struct {
	Text       string
	Confidence float64
	X1         float32
	Y1         float32
	X2         float32
	Y2         float32
}

// YouTubeHandler extracts transcripts from YouTube videos
type YouTubeHandler interface {
	// GetTranscript fetches the transcript for a YouTube video
	GetTranscript(ctx context.Context, videoID string) (*TranscriptResult, error)
	// ExtractVideoIDFromURL extracts the video ID from a YouTube URL
	ExtractVideoIDFromURL(url string) (string, error)
}

// TranscriptResult contains the output of transcript extraction
type TranscriptResult struct {
	// Full transcript text
	Transcript string
	// Language of the transcript
	Language string
	// Individual segments with timestamps
	Segments []TranscriptSegment
	// Whether transcript was auto-generated
	IsAutoGenerated bool
	// Duration of video in seconds
	Duration int
}

// TranscriptSegment represents a portion of transcript with timestamp
type TranscriptSegment struct {
	// Text for this segment
	Text string
	// Start time in seconds
	StartSeconds int
	// End time in seconds
	EndSeconds int
}

// MediaProcessor orchestrates extraction based on media type
type MediaProcessor interface {
	// ProcessMediaItem extracts content from a media item
	ProcessMediaItem(ctx context.Context, mediaItem *MediaItem) (*ExtractedContent, error)
}

// MediaItem represents a media file to be processed
type MediaItem struct {
	ID            string
	ProjectID     string
	SourceID      string
	Type          string // "image", "video", "youtube", "pdf", "audio"
	URL           string
	ExternalID    string // YouTube video ID, etc.
	FileSizeBytes int
	CreatedAt     string // RFC3339 timestamp
}

// ExtractedContent is the result of media processing
type ExtractedContent struct {
	// Media item ID that was processed
	MediaItemID string
	// The extracted text
	Text string
	// Type of content: "text", "transcript", etc.
	ContentType string
	// Confidence score (0-1)
	Confidence float64
	// Language of extracted content
	Language string
	// When extraction was performed
	ExtractedAt string
	// Additional metadata (segments, video_id, etc.)
	Metadata map[string]interface{}
	// Status: "success", "partial", "failed"
	Status string
}

// Config holds configuration for media handlers
type Config struct {
	// Google Cloud credentials (for OCR)
	GoogleCredentialsPath string
	// YouTube API key (if using authenticated API)
	GoogleAPIKey string
	// YouTube API key (if using authenticated API)
	YouTubeAPIKey string
	// Default language for OCR
	DefaultLanguage string
	// Retry configuration
	MaxRetries int
	// milliseconds
	RetryDelay int
}

// Errors
var (
	ErrInvalidMediaType = fmt.Errorf("invalid media type")
	ErrInvalidURL       = fmt.Errorf("invalid URL")
	ErrExtractionFailed = fmt.Errorf("extraction failed")
	ErrUnauthorized     = fmt.Errorf("unauthorized (check API credentials)")
)
