package media

import (
	"context"
	"fmt"
	"log/slog"
	"os"
)

// VideoTranscriber handles transcription of direct video files (non-YouTube)
// Uses speech-to-text services like Whisper, AssemblyAI, or similar
type VideoTranscriber struct {
	logger *slog.Logger
	apiKey string
}

// NewVideoTranscriber creates a new video transcriber
func NewVideoTranscriber(logger *slog.Logger) *VideoTranscriber {
	if logger == nil {
		logger = slog.Default()
	}

	// Check for API keys in environment
	apiKey := os.Getenv("WHISPER_API_KEY")
	if apiKey == "" {
		apiKey = os.Getenv("ASSEMBLYAI_API_KEY")
	}
	if apiKey == "" {
		apiKey = os.Getenv("OPENAI_API_KEY") // OpenAI Whisper
	}

	if apiKey == "" {
		logger.Warn("No transcription API key found (WHISPER_API_KEY, ASSEMBLYAI_API_KEY, or OPENAI_API_KEY), will use mock mode")
	}

	return &VideoTranscriber{
		logger: logger,
		apiKey: apiKey,
	}
}

// TranscribeFromURL transcribes a video from a URL
func (v *VideoTranscriber) TranscribeFromURL(ctx context.Context, videoURL string) (*TranscriptResult, error) {
	v.logger.Info("Transcribing video from URL", "url", videoURL)

	if v.apiKey != "" {
		return v.transcribeWithAPI(ctx, videoURL)
	}

	// Mock mode - return sample transcript
	return v.getMockTranscript(videoURL), nil
}

// TranscribeFromFile transcribes a local video file
func (v *VideoTranscriber) TranscribeFromFile(ctx context.Context, filePath string) (*TranscriptResult, error) {
	v.logger.Info("Transcribing video from file", "path", filePath)

	// Check if file exists
	if _, err := os.Stat(filePath); err != nil {
		return nil, fmt.Errorf("failed to read video file: %w", err)
	}

	if v.apiKey != "" {
		return v.transcribeFileWithAPI(ctx, filePath)
	}

	// Mock mode - return sample transcript
	return v.getMockTranscript(filePath), nil
}

// transcribeWithAPI transcribes video using API service
func (v *VideoTranscriber) transcribeWithAPI(_ context.Context, videoURL string) (*TranscriptResult, error) {
	// Placeholder for real API integration
	// This would call Whisper, AssemblyAI, etc.
	v.logger.Warn("Video transcription API not yet implemented", "url", videoURL)

	return &TranscriptResult{
		Transcript:      "[API Placeholder] Video transcription not yet implemented. Configure WHISPER_API_KEY or ASSEMBLYAI_API_KEY.",
		Language:        "en",
		Segments:        []TranscriptSegment{},
		IsAutoGenerated: true,
		Duration:        0,
	}, nil
}

// transcribeFileWithAPI transcribes local file using API service
func (v *VideoTranscriber) transcribeFileWithAPI(_ context.Context, filePath string) (*TranscriptResult, error) {
	// Placeholder for real API integration
	v.logger.Warn("Video file transcription API not yet implemented", "path", filePath)

	return &TranscriptResult{
		Transcript:      "[API Placeholder] Video file transcription not yet implemented. Configure WHISPER_API_KEY or ASSEMBLYAI_API_KEY.",
		Language:        "en",
		Segments:        []TranscriptSegment{},
		IsAutoGenerated: true,
		Duration:        0,
	}, nil
}

// getMockTranscript returns mock transcript for testing
func (v *VideoTranscriber) getMockTranscript(identifier string) *TranscriptResult {
	v.logger.Debug("Returning mock video transcript", "identifier", identifier)

	return &TranscriptResult{
		Transcript: fmt.Sprintf("[Mock Video Transcript] This is a mock transcript for video: %s\n\nNote: For production use, implement video transcription with:\n1. OpenAI Whisper API (set OPENAI_API_KEY)\n2. AssemblyAI (set ASSEMBLYAI_API_KEY)\n3. Or local Whisper model\n\nSupported formats: MP4, AVI, MOV, MKV, WebM", identifier),
		Language:   "en",
		Segments: []TranscriptSegment{
			{
				Text:         "[Mock] Video segment 1: Introduction",
				StartSeconds: 0,
				EndSeconds:   15,
			},
			{
				Text:         "[Mock] Video segment 2: Main content discussion",
				StartSeconds: 15,
				EndSeconds:   45,
			},
			{
				Text:         "[Mock] Video segment 3: Conclusion and summary",
				StartSeconds: 45,
				EndSeconds:   60,
			},
		},
		IsAutoGenerated: true,
		Duration:        60,
	}
}

// GetSupportedFormats returns list of supported video formats
func (v *VideoTranscriber) GetSupportedFormats() []string {
	return []string{"mp4", "avi", "mov", "mkv", "webm", "flv", "wmv", "m4v"}
}

// EstimateProcessingTime estimates transcription time based on video duration
func (v *VideoTranscriber) EstimateProcessingTime(durationSeconds int) int {
	// Typically transcription takes ~10-30% of video duration with modern APIs
	return durationSeconds / 3 // Conservative estimate
}
