package media

import (
	"context"
	"fmt"
	"log/slog"
	"regexp"
)

// YouTubeTranscriptFetcher fetches transcripts from YouTube videos using public APIs
type YouTubeTranscriptFetcher struct {
	logger *slog.Logger
}

// NewYouTubeTranscriptFetcher creates a new YouTube transcript fetcher
func NewYouTubeTranscriptFetcher(logger *slog.Logger) *YouTubeTranscriptFetcher {
	if logger == nil {
		logger = slog.Default()
	}

	return &YouTubeTranscriptFetcher{
		logger: logger,
	}
}

// GetTranscript fetches the transcript for a YouTube video
func (y *YouTubeTranscriptFetcher) GetTranscript(ctx context.Context, videoID string) (*TranscriptResult, error) {
	if videoID == "" {
		return nil, fmt.Errorf("%w: video ID is empty", ErrInvalidURL)
	}

	y.logger.Info("Fetching YouTube transcript", "videoID", videoID)

	// Try to fetch transcript from YouTube's public transcript endpoint
	transcript, language, segments, err := y.fetchTranscriptFromAPI(ctx, videoID)
	if err != nil {
		y.logger.Warn("Failed to fetch transcript from API", "error", err, "videoID", videoID)
		// Return mock for testing
		return y.getMockTranscript(videoID), nil
	}

	if transcript == "" {
		y.logger.Debug("No transcript content returned")
		return y.getMockTranscript(videoID), nil
	}

	y.logger.Info("Transcript fetched successfully",
		"videoID", videoID,
		"textLength", len(transcript),
		"language", language,
		"segmentCount", len(segments))

	return &TranscriptResult{
		Transcript:      transcript,
		Language:        language,
		Segments:        segments,
		IsAutoGenerated: false,
		Duration:        0, // Not provided by transcript API
	}, nil
}

// fetchTranscriptFromAPI attempts to fetch transcript from YouTube's API
func (y *YouTubeTranscriptFetcher) fetchTranscriptFromAPI(ctx context.Context, videoID string) (string, string, []TranscriptSegment, error) {
	// Construct the YouTube video page URL to extract captions
	// This is a simplified approach - in production, would use proper API
	y.logger.Debug("Attempting to fetch transcript via API", "videoID", videoID)

	// Return empty for now - placeholder for real implementation
	return "", "en", []TranscriptSegment{}, fmt.Errorf("transcript API not yet implemented")
}

// getMockTranscript returns mock transcript data for testing
func (y *YouTubeTranscriptFetcher) getMockTranscript(videoID string) *TranscriptResult {
	y.logger.Debug("Returning mock transcript", "videoID", videoID)

	return &TranscriptResult{
		Transcript: fmt.Sprintf("[Mock Transcript] This is a mock transcript for YouTube video: %s\n\nNote: For production use, implement proper YouTube Transcript API integration.\n\nTo get real transcripts:\n1. Use youtube-transcript-api Python package\n2. Or call YouTube's official API with API key\n3. Or implement web scraping of captions", videoID),
		Language:   "en",
		Segments: []TranscriptSegment{
			{
				Text:         "[Mock] Segment 1: Introduction",
				StartSeconds: 0,
				EndSeconds:   30,
			},
			{
				Text:         "[Mock] Segment 2: Main content",
				StartSeconds: 30,
				EndSeconds:   60,
			},
			{
				Text:         "[Mock] Segment 3: Conclusion",
				StartSeconds: 60,
				EndSeconds:   90,
			},
		},
		IsAutoGenerated: true,
		Duration:        0,
	}
}

// ExtractVideoIDFromURL extracts the video ID from a YouTube URL
func (y *YouTubeTranscriptFetcher) ExtractVideoIDFromURL(youtubeURL string) (string, error) {
	patterns := []string{
		`(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&\n?#]+)`,
		`youtube\.com\/embed\/([^&\n?#]+)`,
		`youtube\.com\/v\/([^&\n?#]+)`,
	}

	for _, pattern := range patterns {
		re := regexp.MustCompile(pattern)
		matches := re.FindStringSubmatch(youtubeURL)
		if len(matches) > 1 {
			return matches[1], nil
		}
	}

	return "", fmt.Errorf("%w: could not extract video ID from %s", ErrInvalidURL, youtubeURL)
}
