# golangci-lint configuration for cgap

version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - misspell
    - unparam
    - bodyclose
    - exhaustive
    - noctx
    - revive

issues:
  exclude-dirs:
    - vendor
    - node_modules
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
    - linters:
        - staticcheck
      text: "SA1019"
