# golangci-lint configuration for cgap

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - node_modules

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - linters
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - golint
    - gosimple
    - misspell
    - unparam
    - bodyclose
    - exhaustive
    - noctx
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
    - linters:
        - staticcheck
      text: "SA1019"
