# golangci-lint configuration for cgap
version: 2


run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  disable:
    - errcheck
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gosec
    - unparam
    - unused

linters-settings:
  goconst:
    min-occurrences: 5
  gosec:
    excludes:
      - G107
      - G304

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G104: Errors unhandled"
    - linters:
        - gosec
      text: "G107: Potential HTTP request made with variable url"
    - linters:
        - gosec
      text: "G304: Potential file inclusion via variable"

